Repository kubernetes-sigs/ibm-powervs-block-csi-driver, pull requests merged in 2023-09, with the labels that each got.

#457 Add govulncheck target in Makefile
  Makefile
Labels: kind/feature, lgtm, size/XS, approved, cncf-cla: yes

#469 Cleanup: refactor powervs cloud to remove extra params
  pkg/cloud/powervs.go
Labels: kind/cleanup, size/S, lgtm, approved, cncf-cla: yes

#465 Update the powervs-csi-node to use nodeSelector for ppc64le
  deploy/kubernetes/base/node.yaml
Labels: kind/bug, ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#463 Using env vars for getting the metadata details
  pkg/driver/controller.go
  pkg/driver/node.go
Labels: kind/feature, size/M, lgtm, approved, cncf-cla: yes

#477 Improve delete device failure logs in driver node
  pkg/device/multipath.go
Labels: size/S, lgtm, approved, cncf-cla: yes

#473 Manually bump k8s.io/kubernetes from 1.28.1 to 1.28.2
  go.mod
  go.sum
Labels: kind/cleanup, lgtm, approved, size/L, cncf-cla: yes
