Repository kubernetes-sigs/ibm-powervs-block-csi-driver, pull requests merged in 2024-07, with the labels that each got.

#687 Supress kustomize warnings for deprecated fields
  deploy/kubernetes/base/kustomization.yaml
  deploy/kubernetes/overlays/dev/kustomization.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: size/M, kind/cleanup, ok-to-test, lgtm, approved, cncf-cla: yes

#688 Use livenessprobe:v2.12.0.
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: kind/bug, ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#673 Update Go version to 1.22.
  Dockerfile
  README.md
  go.mod
Labels: kind/cleanup, ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#695 Bump sidecar images for CSI driver
  deploy/kubernetes/base/controller.yaml
  deploy/kubernetes/base/node.yaml
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: needs-ok-to-test, kind/cleanup, size/S, lgtm, approved, cncf-cla: yes

#705 Bump CentOS image to stream 9
  build/base/Dockerfile
Labels: needs-ok-to-test, kind/cleanup, lgtm, size/XS, approved, cncf-cla: yes

#674 Refactor small sections of code and tests
  Makefile
  README.md
  adhoc-controllers/controllers/nodeupdate_controller.go
  adhoc-controllers/main.go
  cmd/main.go
  cmd/options.go
  go.mod
  pkg/cloud/cloud_interface.go
  pkg/cloud/metadata.go
  pkg/cloud/mocks/mock_cloud.go
  pkg/cloud/powervs.go
  pkg/cloud/powervs_node.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/sanity_test.go
  pkg/driver/validation.go
  pkg/driver/validation_test.go
  tests/e2e/README.md
  tests/e2e/pre_provisioning.go
  tests/e2e/suite_test.go
  tests/e2e/testsuites/testsuites.go
  tests/remote/pi_resources.go
Labels: kind/cleanup, ok-to-test, lgtm, approved, size/L, cncf-cla: yes

#676 Add note for Power VS Private support
  README.md
Labels: needs-ok-to-test, lgtm, size/XS, approved, kind/documentation, cncf-cla: yes

#708 Post-release v0.7.0 changes to the release branch
  README.md
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: lgtm, size/XS, approved, kind/documentation, cncf-cla: yes

#710 Update devtools to latest available versions
  Makefile
  hack/verify-all
Labels: needs-ok-to-test, kind/cleanup, lgtm, size/XS, approved, cncf-cla: yes
