Repository kubernetes-sigs/ibm-powervs-block-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#849 fixed bug in integration test
  tests/it/utils.go
Labels: ok-to-test, lgtm, size/XS, approved, cncf-cla: yes, kind/test

#856 Upgrade k8s and deps to latest
  README.md
  go.mod
  go.sum
Labels: kind/cleanup, lgtm, approved, size/L, cncf-cla: yes

#860 Release v0.9.0
  README.md
  deploy/kubernetes/overlays/stable/kustomization.yaml
Labels: size/S, lgtm, approved, kind/documentation, cncf-cla: yes

#866 Update the staging link to artifact registry and some minor changes
  RELEASE.md
Labels: size/S, lgtm, approved, kind/documentation, cncf-cla: yes
