Repository kubernetes-sigs/ibm-powervs-block-csi-driver, pull requests merged in 2025-02, with the labels that each got.

#816 Added coverage to make test
  .gitignore
  hack/test.sh
Labels: size/M, ok-to-test, lgtm, approved, cncf-cla: yes, kind/test

#833 Remove execinquery linter
  .golangci.yml
Labels: kind/bug, needs-ok-to-test, lgtm, size/XS, approved, cncf-cla: yes

#825 Add support for volume clone operations through CSI driver
  pkg/cloud/cloud_interface.go
  pkg/cloud/mocks/mock_cloud.go
  pkg/cloud/powervs.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/sanity_test.go
Labels: kind/feature, ok-to-test, lgtm, approved, size/L, cncf-cla: yes

#843 Upgrade k8s deps for Security fix
  go.mod
  go.sum
Labels: size/M, kind/cleanup, lgtm, approved, cncf-cla: yes

#842 Fix for Integration Test failure
  tests/remote/pi_resources.go
Labels: kind/bug, size/S, lgtm, approved, cncf-cla: yes
